### ISSUE TITLE
Upstream http4s linters

### ISSUE THREAD

**Issue by armanbilge** [typelevel/typelevel-scalafix#1]
https://github.com/http4s/http4s/tree/series/0.23/scalafix-internal/rules/src/main/scala-2/fix

Notably:
- "no fs2 sync compiler"
  https://github.com/http4s/http4s/blob/fab4d97e23398a8e33d2643e140a3e8e913506bb/scalafix-internal/rules/src/main/scala-2/fix/Fs2Linters.scala#L37

**Comment by armanbilge** [comment]
Couple thoughts questions on the remaining rules to port:
1. The `GeneralLinters` are mostly specific to Scala (OSS) library hygiene, so I reckon they deserve their own module specifically for that `typelevel-scalafix-library` or something?
    https://github.com/http4s/http4s/blob/cc9bf545feedebbf3f59e8b57f29b8be8baf1681/scalafix-internal/rules/src/main/scala-2/fix/GeneralLinters.scala
3. Does it make sense to have a module for http4s-specific rules here? I'm inclined to say yes, but we could easily host a sister project in http4s org as well.

**Comment by DavidGregory084** [comment]
>     1. The `GeneralLinters` are mostly specific to Scala (OSS) library hygiene, so I reckon they deserve their own module specifically for that `typelevel-scalafix-library` or something? Edit: even better I'd love to upstream these to scalafix, but I'm not sure what their criteria are.

Yeah, let's add a `typelevel-scalafix-core` to capture "Typelevel Scala style" rules that aren't specific to any library?

>     2. Does it make sense to have a module for http4s-specific rules here? I'm inclined to say yes, but we could easily host a sister project in http4s org as well.

Yeah absolutely, http4s is a Typelevel library after all :+1:

**Comment by armanbilge** [comment]
I opened an issue to see if scalafix itself will take the `GeneralLinters`. If so, we can close this issue as complete :)
- https://github.com/scalacenter/scalafix/issues/1621

**Comment by armanbilge** [comment]
Looks like Scalafix will take the `GeneralLinters`, so our work here is done 🚀
