### ISSUE TITLE
Artifacts cannot be found

### ISSUE THREAD

**Issue by NeQuissimus** [typelevel/typelevel-scalafix#9]
@armanbilge @DavidGregory084 

Hey, I tried adding these Scalafix rules to a project of mine.
I added `resolvers += Resolver.sonatypeRepo("snapshots")` into my `project/plugins.sbt` but the artifacts cannot be found.
Browsing https://oss.sonatype.org/content/repositories/snapshots/org/typelevel/ does not show any `typelevel-scalafix` folders at all.
Have the latest snapshots been expired? :)
Could you maybe publish a 0.1 tag to push a JAR into the release channel?

Thank you :)

**Comment by armanbilge** [comment]
@NeQuissimus snapshots are available here:

https://s01.oss.sonatype.org/content/repositories/snapshots/org/typelevel/typelevel-scalafix-cats_2.13/

You'll need to add the S01 host to your resolvers.

**Comment by NeQuissimus** [comment]
Oh, my bad. I guess I just looked in the wrong place :)
Thank you!

**Comment by armanbilge** [comment]
No worries! We will be releasing 0.1.0 shortly :)
